name: testing
on:
  workflow_dispatch:
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.0
    - name: sh
      shell: bash
      run: echo "Hello World"
    - name: sh
      shell: bash
      run: |-
        echo "Multiline shell steps works too"
        ls -lah
